# Generated by Django 5.1.2 on 2024-12-21 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='record',
        ),
        migrations.AddField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clinic_app.patient'),
            preserve_default=False,
        ),
    ]
